
name: React test

on: [push]

jobs:
  unity_tests:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Test with jest
      run: |
        npm install
        npm test
  
  cypress_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.3
    - name: Cypress.io
      uses: cypress-io/github-action@v5.8.2
      with:
        start: npm start
      
